# Generated by Django 4.1.4 on 2022-12-07 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='наименование')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='время создания')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='время изменения')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='активен')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('id',),
            },
        ),
    ]
