# Generated by Django 4.1.4 on 2022-12-07 12:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=250, unique=True, verbose_name='наименование'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='наименование')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='время создания')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='время изменения')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='активен')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('right_answers', models.CharField(default='1,', max_length=50)),
                ('answer_01', models.CharField(default='default', max_length=150)),
                ('answer_02', models.CharField(default='default', max_length=150)),
                ('answer_03', models.CharField(default='default', max_length=150)),
                ('answer_04', models.CharField(default='default', max_length=150)),
                ('category', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='quizapp.category')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ('id',),
            },
        ),
    ]
