# Generated by Django 4.1.4 on 2022-12-08 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_alter_category_title_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='наименование')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='время создания')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='время изменения')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='активен')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('questions', models.ManyToManyField(to='quizapp.question')),
            ],
            options={
                'verbose_name': 'Набор тестов',
                'verbose_name_plural': 'Наборы тестов',
                'ordering': ('id',),
            },
        ),
    ]
