# Generated by Django 4.1.4 on 2022-12-08 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_question_content_question_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_01',
            field=models.CharField(default='default', max_length=150, verbose_name='ответ №1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_02',
            field=models.CharField(default='default', max_length=150, verbose_name='ответ №2'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_03',
            field=models.CharField(default='default', max_length=150, verbose_name='ответ №3'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_04',
            field=models.CharField(default='default', max_length=150, verbose_name='ответ №4'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='quizapp.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.CharField(default='question', max_length=250, verbose_name='текст вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='right_answers',
            field=models.CharField(default='1,', max_length=50, verbose_name='правильный ответ/ответы'),
        ),
    ]
