# Generated by Django 4.1.4 on 2022-12-12 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='наименование')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='время создания')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='время изменения')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='активен')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('card_series', models.CharField(max_length=20, verbose_name='серия карты')),
                ('card_number', models.CharField(max_length=20, verbose_name='номер карты')),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата выпуска карты')),
                ('expiration_date', models.DateTimeField(blank=True, verbose_name='дата окончания действия')),
                ('card_status', models.CharField(choices=[('AC', 'активирована'), ('DE', 'деактивирована'), ('EX', 'просрочена')], db_index=True, default='DE', max_length=2, verbose_name='статус карты')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карты',
                'ordering': ('id',),
            },
        ),
    ]
