# Generated by Django 4.1.4 on 2022-12-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_app', '0002_alter_card_card_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата окончания действия'),
        ),
    ]
