# Generated by Django 4.1.4 on 2022-12-13 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_app', '0003_alter_card_expiration_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('expiration_date', 'id'), 'verbose_name': 'Карта', 'verbose_name_plural': 'Карты'},
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2050, 1, 1, 0, 0), verbose_name='дата окончания действия'),
        ),
    ]
