# Generated by Django 4.1.4 on 2022-12-13 13:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cards_app', '0005_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-use_time'], 'verbose_name': 'Покупка по карте', 'verbose_name_plural': 'Покупки по карте'},
        ),
        migrations.AlterField(
            model_name='order',
            name='card_used',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards_app.card', to_field='title', verbose_name='использованная карта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='сумма покупки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='use_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='время использования карты'),
        ),
    ]
